# coding: utf-8

"""
    Connector Service API

    The Connector Service provides a unified API for accessing Data Products, validating Contracts, and logging Transactions in the NextGen node.

    The version of the OpenAPI document: 0.1.0
    Contact: all-hiro@hiro-microdatacenters.nl
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ds_connector_service.api.data_products_api import DataProductsApi


class TestDataProductsApi(unittest.TestCase):
    """DataProductsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DataProductsApi()

    def tearDown(self) -> None:
        pass

    def test_get_connector_metadata(self) -> None:
        """Test case for get_connector_metadata

        Get Connector Metadata
        """
        pass

    def test_get_dataproduct_chunk(self) -> None:
        """Test case for get_dataproduct_chunk

        Get Data Product Chunk
        """
        pass

    def test_get_dataproduct_content(self) -> None:
        """Test case for get_dataproduct_content

        Get Data Product Content
        """
        pass

    def test_get_distribution_metadata(self) -> None:
        """Test case for get_distribution_metadata

        Get Distribution Metadata
        """
        pass

    def test_health_check(self) -> None:
        """Test case for health_check

        Health Check
        """
        pass

    def test_list_dataproduct_distributions(self) -> None:
        """Test case for list_dataproduct_distributions

        List Data Product Distributions
        """
        pass

    def test_list_dataproducts(self) -> None:
        """Test case for list_dataproducts

        List Data Products
        """
        pass


if __name__ == '__main__':
    unittest.main()
