# coding: utf-8

"""
    Connector Service API

    The Connector Service provides a unified API for accessing Data Products, validating Contracts, and logging Transactions in the NextGen node.

    The version of the OpenAPI document: 0.1.0
    Contact: all-hiro@hiro-microdatacenters.nl
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ds_connector_service.models.data_product_item import DataProductItem

class TestDataProductItem(unittest.TestCase):
    """DataProductItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DataProductItem:
        """Test DataProductItem
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DataProductItem`
        """
        model = DataProductItem()
        if include_optional:
            return DataProductItem(
                distribution = [
                    ds_connector_service.models.data_product_distribution.DataProductDistribution(
                        access_service = null, 
                        access_url = null, 
                        byte_size = null, 
                        compress_format = null, 
                        download_url = null, 
                        media_type = null, 
                        package_format = null, 
                        access_rights = null, 
                        conforms_to = null, 
                        description = null, 
                        format = null, 
                        issued = null, 
                        license = null, 
                        modified = null, 
                        rights = null, 
                        title = null, 
                        has_policy = null, 
                        checksum = null, )
                    ],
                region = ''
            )
        else:
            return DataProductItem(
                distribution = [
                    ds_connector_service.models.data_product_distribution.DataProductDistribution(
                        access_service = null, 
                        access_url = null, 
                        byte_size = null, 
                        compress_format = null, 
                        download_url = null, 
                        media_type = null, 
                        package_format = null, 
                        access_rights = null, 
                        conforms_to = null, 
                        description = null, 
                        format = null, 
                        issued = null, 
                        license = null, 
                        modified = null, 
                        rights = null, 
                        title = null, 
                        has_policy = null, 
                        checksum = null, )
                    ],
        )
        """

    def testDataProductItem(self):
        """Test DataProductItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
