# coding: utf-8

"""
    Connector Service API

    The Connector Service provides a unified API for accessing Data Products, validating Contracts, and logging Transactions in the NextGen node.

    The version of the OpenAPI document: 0.1.0
    Contact: all-hiro@hiro-microdatacenters.nl
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ds_connector_service.models.connector_metadata import ConnectorMetadata

class TestConnectorMetadata(unittest.TestCase):
    """ConnectorMetadata unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ConnectorMetadata:
        """Test ConnectorMetadata
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ConnectorMetadata`
        """
        model = ConnectorMetadata()
        if include_optional:
            return ConnectorMetadata(
                connector_id = '',
                region = '',
                supported_interfaces = [
                    ''
                    ],
                status = '',
                version = ''
            )
        else:
            return ConnectorMetadata(
                connector_id = '',
                region = '',
                supported_interfaces = [
                    ''
                    ],
                status = '',
                version = '',
        )
        """

    def testConnectorMetadata(self):
        """Test ConnectorMetadata"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
