# coding: utf-8

"""
    Connector Service API

    The Connector Service provides a unified API for accessing Data Products, validating Contracts, and logging Transactions in the NextGen node.

    The version of the OpenAPI document: 0.1.0
    Contact: all-hiro@hiro-microdatacenters.nl
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ds_connector_service.models.data_product_distribution import DataProductDistribution

class TestDataProductDistribution(unittest.TestCase):
    """DataProductDistribution unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DataProductDistribution:
        """Test DataProductDistribution
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DataProductDistribution`
        """
        model = DataProductDistribution()
        if include_optional:
            return DataProductDistribution(
                access_service = None,
                access_url = None,
                byte_size = None,
                compress_format = None,
                download_url = None,
                media_type = None,
                package_format = None,
                access_rights = None,
                conforms_to = None,
                description = None,
                format = None,
                issued = None,
                license = None,
                modified = None,
                rights = None,
                title = None,
                has_policy = None,
                checksum = None
            )
        else:
            return DataProductDistribution(
        )
        """

    def testDataProductDistribution(self):
        """Test DataProductDistribution"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
