# coding: utf-8

"""
    Connector Service API

    The Connector Service provides a unified API for accessing Data Products, validating Contracts, and logging Transactions in the NextGen node.

    The version of the OpenAPI document: 0.1.0
    Contact: all-hiro@hiro-microdatacenters.nl
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ds_connector_service.models.tags1 import Tags1

class TestTags1(unittest.TestCase):
    """Tags1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Tags1:
        """Test Tags1
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Tags1`
        """
        model = Tags1()
        if include_optional:
            return Tags1(
            )
        else:
            return Tags1(
        )
        """

    def testTags1(self):
        """Test Tags1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
