# coding: utf-8

"""
    Connector Service API

    The Connector Service provides a unified API for accessing Data Products, validating Contracts, and logging Transactions in the NextGen node.

    The version of the OpenAPI document: 0.1.0
    Contact: all-hiro@hiro-microdatacenters.nl
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class DataProductDistribution(BaseModel):
    """
    Standardized metadata for resources across different sources
    """ # noqa: E501
    access_service: Optional[StrictStr] = None
    access_url: Optional[StrictStr] = None
    byte_size: Optional[StrictInt] = None
    compress_format: Optional[StrictStr] = None
    download_url: Optional[StrictStr] = None
    media_type: Optional[StrictStr] = None
    package_format: Optional[StrictStr] = None
    access_rights: Optional[StrictStr] = None
    conforms_to: Optional[StrictStr] = None
    description: Optional[StrictStr] = None
    format: Optional[StrictStr] = None
    issued: Optional[StrictStr] = None
    license: Optional[StrictStr] = None
    modified: Optional[StrictStr] = None
    rights: Optional[StrictStr] = None
    title: Optional[StrictStr] = None
    has_policy: Optional[StrictStr] = None
    checksum: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["access_service", "access_url", "byte_size", "compress_format", "download_url", "media_type", "package_format", "access_rights", "conforms_to", "description", "format", "issued", "license", "modified", "rights", "title", "has_policy", "checksum"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DataProductDistribution from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if access_service (nullable) is None
        # and model_fields_set contains the field
        if self.access_service is None and "access_service" in self.model_fields_set:
            _dict['access_service'] = None

        # set to None if access_url (nullable) is None
        # and model_fields_set contains the field
        if self.access_url is None and "access_url" in self.model_fields_set:
            _dict['access_url'] = None

        # set to None if byte_size (nullable) is None
        # and model_fields_set contains the field
        if self.byte_size is None and "byte_size" in self.model_fields_set:
            _dict['byte_size'] = None

        # set to None if compress_format (nullable) is None
        # and model_fields_set contains the field
        if self.compress_format is None and "compress_format" in self.model_fields_set:
            _dict['compress_format'] = None

        # set to None if download_url (nullable) is None
        # and model_fields_set contains the field
        if self.download_url is None and "download_url" in self.model_fields_set:
            _dict['download_url'] = None

        # set to None if media_type (nullable) is None
        # and model_fields_set contains the field
        if self.media_type is None and "media_type" in self.model_fields_set:
            _dict['media_type'] = None

        # set to None if package_format (nullable) is None
        # and model_fields_set contains the field
        if self.package_format is None and "package_format" in self.model_fields_set:
            _dict['package_format'] = None

        # set to None if access_rights (nullable) is None
        # and model_fields_set contains the field
        if self.access_rights is None and "access_rights" in self.model_fields_set:
            _dict['access_rights'] = None

        # set to None if conforms_to (nullable) is None
        # and model_fields_set contains the field
        if self.conforms_to is None and "conforms_to" in self.model_fields_set:
            _dict['conforms_to'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if format (nullable) is None
        # and model_fields_set contains the field
        if self.format is None and "format" in self.model_fields_set:
            _dict['format'] = None

        # set to None if issued (nullable) is None
        # and model_fields_set contains the field
        if self.issued is None and "issued" in self.model_fields_set:
            _dict['issued'] = None

        # set to None if license (nullable) is None
        # and model_fields_set contains the field
        if self.license is None and "license" in self.model_fields_set:
            _dict['license'] = None

        # set to None if modified (nullable) is None
        # and model_fields_set contains the field
        if self.modified is None and "modified" in self.model_fields_set:
            _dict['modified'] = None

        # set to None if rights (nullable) is None
        # and model_fields_set contains the field
        if self.rights is None and "rights" in self.model_fields_set:
            _dict['rights'] = None

        # set to None if title (nullable) is None
        # and model_fields_set contains the field
        if self.title is None and "title" in self.model_fields_set:
            _dict['title'] = None

        # set to None if has_policy (nullable) is None
        # and model_fields_set contains the field
        if self.has_policy is None and "has_policy" in self.model_fields_set:
            _dict['has_policy'] = None

        # set to None if checksum (nullable) is None
        # and model_fields_set contains the field
        if self.checksum is None and "checksum" in self.model_fields_set:
            _dict['checksum'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DataProductDistribution from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "access_service": obj.get("access_service"),
            "access_url": obj.get("access_url"),
            "byte_size": obj.get("byte_size"),
            "compress_format": obj.get("compress_format"),
            "download_url": obj.get("download_url"),
            "media_type": obj.get("media_type"),
            "package_format": obj.get("package_format"),
            "access_rights": obj.get("access_rights"),
            "conforms_to": obj.get("conforms_to"),
            "description": obj.get("description"),
            "format": obj.get("format"),
            "issued": obj.get("issued"),
            "license": obj.get("license"),
            "modified": obj.get("modified"),
            "rights": obj.get("rights"),
            "title": obj.get("title"),
            "has_policy": obj.get("has_policy"),
            "checksum": obj.get("checksum")
        })
        return _obj


