# coding: utf-8

"""
    Connector Service API

    The Connector Service provides a unified API for accessing Data Products, validating Contracts, and logging Transactions in the NextGen node.

    The version of the OpenAPI document: 0.1.0
    Contact: all-hiro@hiro-microdatacenters.nl
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel
from typing import Any, ClassVar, Dict, List, Optional
from ds_connector_service.models.access_rights import AccessRights
from ds_connector_service.models.access_service import AccessService
from ds_connector_service.models.access_url import AccessUrl
from ds_connector_service.models.byte_size import ByteSize
from ds_connector_service.models.checksum import Checksum
from ds_connector_service.models.compress_format import CompressFormat
from ds_connector_service.models.conforms_to import ConformsTo
from ds_connector_service.models.description import Description
from ds_connector_service.models.download_url import DownloadUrl
from ds_connector_service.models.format import Format
from ds_connector_service.models.has_policy import HasPolicy
from ds_connector_service.models.issued import Issued
from ds_connector_service.models.license import License
from ds_connector_service.models.media_type import MediaType
from ds_connector_service.models.modified import Modified
from ds_connector_service.models.package_format import PackageFormat
from ds_connector_service.models.rights import Rights
from ds_connector_service.models.title import Title
from typing import Optional, Set
from typing_extensions import Self

class DataProductDistribution(BaseModel):
    """
    Standardized metadata for resources across different sources
    """ # noqa: E501
    access_service: Optional[AccessService] = None
    access_url: Optional[AccessUrl] = None
    byte_size: Optional[ByteSize] = None
    compress_format: Optional[CompressFormat] = None
    download_url: Optional[DownloadUrl] = None
    media_type: Optional[MediaType] = None
    package_format: Optional[PackageFormat] = None
    access_rights: Optional[AccessRights] = None
    conforms_to: Optional[ConformsTo] = None
    description: Optional[Description] = None
    format: Optional[Format] = None
    issued: Optional[Issued] = None
    license: Optional[License] = None
    modified: Optional[Modified] = None
    rights: Optional[Rights] = None
    title: Optional[Title] = None
    has_policy: Optional[HasPolicy] = None
    checksum: Optional[Checksum] = None
    __properties: ClassVar[List[str]] = ["access_service", "access_url", "byte_size", "compress_format", "download_url", "media_type", "package_format", "access_rights", "conforms_to", "description", "format", "issued", "license", "modified", "rights", "title", "has_policy", "checksum"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DataProductDistribution from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of access_service
        if self.access_service:
            _dict['access_service'] = self.access_service.to_dict()
        # override the default output from pydantic by calling `to_dict()` of access_url
        if self.access_url:
            _dict['access_url'] = self.access_url.to_dict()
        # override the default output from pydantic by calling `to_dict()` of byte_size
        if self.byte_size:
            _dict['byte_size'] = self.byte_size.to_dict()
        # override the default output from pydantic by calling `to_dict()` of compress_format
        if self.compress_format:
            _dict['compress_format'] = self.compress_format.to_dict()
        # override the default output from pydantic by calling `to_dict()` of download_url
        if self.download_url:
            _dict['download_url'] = self.download_url.to_dict()
        # override the default output from pydantic by calling `to_dict()` of media_type
        if self.media_type:
            _dict['media_type'] = self.media_type.to_dict()
        # override the default output from pydantic by calling `to_dict()` of package_format
        if self.package_format:
            _dict['package_format'] = self.package_format.to_dict()
        # override the default output from pydantic by calling `to_dict()` of access_rights
        if self.access_rights:
            _dict['access_rights'] = self.access_rights.to_dict()
        # override the default output from pydantic by calling `to_dict()` of conforms_to
        if self.conforms_to:
            _dict['conforms_to'] = self.conforms_to.to_dict()
        # override the default output from pydantic by calling `to_dict()` of description
        if self.description:
            _dict['description'] = self.description.to_dict()
        # override the default output from pydantic by calling `to_dict()` of format
        if self.format:
            _dict['format'] = self.format.to_dict()
        # override the default output from pydantic by calling `to_dict()` of issued
        if self.issued:
            _dict['issued'] = self.issued.to_dict()
        # override the default output from pydantic by calling `to_dict()` of license
        if self.license:
            _dict['license'] = self.license.to_dict()
        # override the default output from pydantic by calling `to_dict()` of modified
        if self.modified:
            _dict['modified'] = self.modified.to_dict()
        # override the default output from pydantic by calling `to_dict()` of rights
        if self.rights:
            _dict['rights'] = self.rights.to_dict()
        # override the default output from pydantic by calling `to_dict()` of title
        if self.title:
            _dict['title'] = self.title.to_dict()
        # override the default output from pydantic by calling `to_dict()` of has_policy
        if self.has_policy:
            _dict['has_policy'] = self.has_policy.to_dict()
        # override the default output from pydantic by calling `to_dict()` of checksum
        if self.checksum:
            _dict['checksum'] = self.checksum.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DataProductDistribution from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "access_service": AccessService.from_dict(obj["access_service"]) if obj.get("access_service") is not None else None,
            "access_url": AccessUrl.from_dict(obj["access_url"]) if obj.get("access_url") is not None else None,
            "byte_size": ByteSize.from_dict(obj["byte_size"]) if obj.get("byte_size") is not None else None,
            "compress_format": CompressFormat.from_dict(obj["compress_format"]) if obj.get("compress_format") is not None else None,
            "download_url": DownloadUrl.from_dict(obj["download_url"]) if obj.get("download_url") is not None else None,
            "media_type": MediaType.from_dict(obj["media_type"]) if obj.get("media_type") is not None else None,
            "package_format": PackageFormat.from_dict(obj["package_format"]) if obj.get("package_format") is not None else None,
            "access_rights": AccessRights.from_dict(obj["access_rights"]) if obj.get("access_rights") is not None else None,
            "conforms_to": ConformsTo.from_dict(obj["conforms_to"]) if obj.get("conforms_to") is not None else None,
            "description": Description.from_dict(obj["description"]) if obj.get("description") is not None else None,
            "format": Format.from_dict(obj["format"]) if obj.get("format") is not None else None,
            "issued": Issued.from_dict(obj["issued"]) if obj.get("issued") is not None else None,
            "license": License.from_dict(obj["license"]) if obj.get("license") is not None else None,
            "modified": Modified.from_dict(obj["modified"]) if obj.get("modified") is not None else None,
            "rights": Rights.from_dict(obj["rights"]) if obj.get("rights") is not None else None,
            "title": Title.from_dict(obj["title"]) if obj.get("title") is not None else None,
            "has_policy": HasPolicy.from_dict(obj["has_policy"]) if obj.get("has_policy") is not None else None,
            "checksum": Checksum.from_dict(obj["checksum"]) if obj.get("checksum") is not None else None
        })
        return _obj


