# Chart values for ds-search
replicaCount: 1

image:
  repository: ""
  tag: ""
  pullPolicy: IfNotPresent
  pullSecret: ""

# Optional: override the namespace; defaults to release namespace
namespace: uva

nameOverride: "ds-connector"
fullnameOverride: "ds-connector"

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

container:
  command: ["uvicorn"]
  args: ["app.main:app", "--host", "0.0.0.0", "--port", "7000"]

livenessProbe:
  httpGet:
    path: /health-check
    port: http
    scheme: HTTP
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
readinessProbe:
  httpGet:
    path: /health-check
    port: http
    scheme: HTTP
  initialDelaySeconds: 20
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 3
  failureThreshold: 3


service:
  type: ClusterIP
  port: 7000

env:
  - name: CHUNK_SIZE
    value: "8192" # 8KB chunks
  - name: MAX_FILE_SIZE
    value: "10737418240"  # 10GB
  - name: MAX_FILES_TO_LIST
    value: "10"  # Limit for number of files to list in directory listings
  - name: FS_BASE_PATH
    value: "/data" # Base path for file system operations
  - name : LOG_LEVEL
    value: "INFO"

resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"

persistence:
  storageClass: "standard"
  size: 10Gi

deploymentMode: deployment


# Optional nodeSelector & tolerations
nodeSelector: {}
tolerations: []

ingress:
  enabled: true
  host: nextgen.hiro-develop.nl

## Update this according to the desired node
nodeSelector:
  role: uva

## To control the metics on development
metrics:
  enabled: true
