name: Test and build connector

on: [push, pull_request, workflow_dispatch]

jobs:
  test_and_build_connector:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install poetry
        run: pip install poetry

      - name: Install dependencies
        run: |
          poetry config virtualenvs.in-project true
          poetry install --no-root --no-cache --no-interaction

      - name: Run linters and type checks
        run: |
          poetry run mypy app
          poetry run flake8 app --count --select=E9,F63,F7,F82 --show-source --statistics
          poetry run black --check app
          poetry run isort --check-only app

      - name: Run tests
        run: poetry run pytest

      # Optional: build docker image for connector
      - name: Build Docker image
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          docker build -t hiro/ds-connector-service:${GITHUB_REF#refs/tags/} .
